### ISSUE TITLE
Windows: Update XAML NuGet Package to 2.6.0

### ISSUE THREAD

**Issue by amdingler** [microsoft/react-native-test-app#444]
### Proposal

I am adding an Expander component to fluentui-react-native which is a native implementation of the WinUI 2.6 Expander control. I cannot add the new component to the test application until it has been upgraded from 2.5.0 to 2.6.0.

### Alternatives

There is not an alternative since the Expander control does not exist on lower versions of the XAML package. If it is possible to update the package on the local application that could also be a solution.

### Implementation Details

I believe `windows/ReactTestApp/packages.config` needs to be updated with the new version. I'm unsure if other changes would need to be made as well since I'm new to the project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
We will also need to bump the version in `/windows/test-app.js` on lines 365, 366, and 370:

https://github.com/microsoft/react-native-test-app/blob/b72bb100d938d417fe7c0228693bcea29b84f37a/windows/test-app.js#L365-L370

This requires that you run `install-windows-test-app --use-nuget` when generating the Windows test app. Otherwise, you must use the version that RNW uses, which is 2.3.191129002 for [0.63](https://github.com/microsoft/react-native-windows/blob/d30bac160ed8880bafee17ededd131006c03f420/vnext/Microsoft.ReactNative/packages.config#L7) and [0.64](https://github.com/microsoft/react-native-windows/blob/87ffd8697101ac77456e2bca7b521c4618f34a28/vnext/Microsoft.ReactNative/packages.config#L7).

I am currently oof until next week. Is this something that you can look into?
